config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'
  resources :questions do
    resources :answers, shallow: true do
      member do
        patch 'set_best'
      end
    end
  end
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  has_many :attachments, as: :attachmentable

  validates :body, :question_id, presence: true

  default_scope { order(best: :desc) }
  accepts_nested_attributes_for :attachments
  def set_best!
    transaction do
      question.answers.update_all(best: false)
      update!(best: true)
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attachment.rb
# frozen_string_literal: true

class Attachment < ApplicationRecord
  belongs_to :attachmentable, polymorphic: true

  mount_uploader :file, FileUploader
end

app/models/question.rb
class Question < ApplicationRecord
has_many :answers, dependent: :destroy
has_many :attachments, as: :attachmentable
belongs_to :user
validates :title, :body, presence: true, uniqueness: true
  validates :user_id, presence: true
  def to_s
    self[:title]
  end
  accepts_nested_attributes_for :attachments
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :answers, dependent: :destroy
  has_many :questions, dependent: :destroy
end

app/models/user_with_question_and_answer.rb
# frozen_string_literal: true

class UserWithQuestionAndAnswer < ApplicationRecord
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :load_answer, only: %i[destroy show update set_best]
  before_action :load_question, only: %i[new create]

  def show; end

  def new
    @answer = @question.answers.new
  end

  def set_best
    @question = @answer.question
    @answer.set_best!
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user_id = current_user.id
    @answer.save
  end

  def destroy
    @question = @answer.question
    @answer.destroy
   end

  private

  def load_question
    @question = Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def answer_params
    params.require(:answer).permit(:body, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :load_question, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_owner, only: %i[destroy edit]

  def show
    @answer = @question.answers.build
    @answer.attachments.build
  end

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
    @question.attachments.build
  end

  def create
    @question = Question.new(question_params)
    @question.user_id = current_user.id

    if @question.save
      flash[:notice] = 'Your question successfully created.'
      redirect_to @question
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_path
  end

  def load_owner
    if @question.user_id != current_user.id
      redirect_to root_path
      flash[:notice] = 'You cannot do this'
    end
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attachments_attributes: [:id, :file, :_destroy])
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/answers/create.js.erb
$('.answers').html('<%= j render 'questions/answers' %>');
$('#answer_body').val('');

app/views/answers/destroy.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  <% if @answer.destroyed? %>
    $('.answers').html('<%= j render 'questions/answers' %>');
    $('<%= "#answer-#{ @answer.id }" %>').remove();
  <% end %>
<% end %>

app/views/answers/set_best.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html('<%= j message %>');
  <% end %>
<% else %>
  $('.answers').html('<%= j render "questions/answers" %>');
<% end %>

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <% @answer.errors.full_messages.each do |message| %>
    $('.answer-errors').html(' <%= j message %>');
  <% end %>
<% else %>
  $('.answers').html('<%= j render 'questions/answers' %>');
  $('.edit-answer-link').click(function(e) {
    e.preventDefault();
    $(this).hide();
    answer_id = $(this).data('answerId');
    $('form#edit-answer-' + answer_id).show();
  });
$(document).ready(ready);
$(document).on('page:load', ready);
$(document).on('page:update', ready);
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qna2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/questions/_answers.html.slim
- @question.answers.each do |answer|
  -if answer.best
    = 'Best answer: '
  -if answer.persisted?
    p = answer.body
    ul
      -answer.attachments.each do |a|
        li = link_to a.file.identifier, a.file.url
  - if user_signed_in? && @question.user_id == current_user.id
    - if user_signed_in? && answer.user_id
      button
        = link_to 'Best', set_best_answer_path(answer), method: :patch, remote: true
  - if user_signed_in? && answer.user_id == current_user.id
    button
      = link_to 'Delete answer', answer_path(answer), method: :delete, remote: true
    button
      = link_to 'Edit answer', '', class: 'edit-answer-link', data: { answer_id: answer.id }
    = form_for answer, remote: true, html: {id: "edit-answer-#{answer.id}"} do |f|
      = f.text_area :body
      = f.submit 'Save'

app/views/questions/edit.html.slim
= form_for @question do |f|
  = f.label :title
  = f.text_area :title
  = f.label :body
  = f.text_area :body
  = f.submit
  = f.button link_to 'Exit', destroy_user_session_path, method: :delete

app/views/questions/index.html.slim
h2 = "A list of questions"
table
  head
      th
        | Title
      th
        | Body
  body
  - @questions.each do |question|
    tr
      td
        = question.title
      td
        = question.body
      td
        button
          = link_to 'Show', question_path(question)
        - if user_signed_in? && question.user_id == current_user.id
          button
            = link_to 'Edit', edit_question_path(question)
          button
            = link_to 'Delete', question_path(question), method: :delete
- if user_signed_in?
  button
    = link_to 'New question', new_question_path
  button
    = link_to 'Exit', destroy_user_session_path, method: :delete
button
  =link_to 'Up', user_session_path

app/views/questions/new.html.slim
= form_for @question do |f|
  p
    = f.label :title
    = f.text_area :title
  p
    = f.label :body
    = f.text_area :body
  p Attachments:
  p
    = f.fields_for :attachments do |a|
      = a.label :file
      = a.file_field :file

  p = f.submit 'Create'

app/views/questions/show.html.slim
h2 = @question.title
p = @question.body
p Attachments:
ul
  -@question.attachments.each do |a|
    li = link_to a.file.identifier, a.file.url

button
  = link_to 'All questions', root_path(@question)
- if user_signed_in? && @question.user_id == current_user.id
  button
    = link_to 'Delete question', question_path(@question), method: :delete
  button
    = link_to 'Edit question', edit_question_path(@question)

h2 All answers for this questions
.answers
  = render 'answers'

= form_for [ @question, @answer ], remote: true do |f|
  p
    h2 = 'your answer'
    .answer-errors
    = f.text_area :body
  p
    = f.fields_for :attachments do |a|
      = a.label :file
      = a.file_field :file
  p = f.submit 'Create answer', method: :create